// import * as reduxActionNames from 'redux-action-names';
export default {
  EMPLOYEES_CREATE_API_CALL: 'EMPLOYEES_CREATE_API_CALL',
  EMPLOYEES_CREATE_START: 'EMPLOYEES_CREATE_START',
  EMPLOYEES_CREATE_SUCCESS: 'EMPLOYEES_CREATE_SUCCESS',
  EMPLOYEES_CREATE_ERROR: 'EMPLOYEES_CREATE_ERROR',

  EMPLOYEES_FETCH_API_CALL: 'EMPLOYEES_FETCH_API_CALL',
  EMPLOYEES_FETCH_START: 'EMPLOYEES_FETCH_START',
  EMPLOYEES_FETCH_SUCCESS: 'EMPLOYEES_FETCH_SUCCESS',
  EMPLOYEES_FETCH_ERROR: 'EMPLOYEES_FETCH_ERROR',

  EMPLOYEE_FETCH_API_CALL: 'EMPLOYEE_FETCH_API_CALL',
  EMPLOYEE_FETCH_START: 'EMPLOYEE_FETCH_START',
  EMPLOYEE_FETCH_SUCCESS: 'EMPLOYEE_FETCH_SUCCESS',
  EMPLOYEE_FETCH_ERROR: 'EMPLOYEE_FETCH_ERROR',

  EMPLOYEES_UPDATE_API_CALL: 'EMPLOYEES_UPDATE_API_CALL',
  EMPLOYEES_UPDATE_START: 'EMPLOYEES_UPDATE_START',
  EMPLOYEES_UPDATE_SUCCESS: 'EMPLOYEES_UPDATE_SUCCESS',
  EMPLOYEES_UPDATE_ERROR: 'EMPLOYEES_UPDATE_ERROR',

  EMPLOYEES_DELETE_API_CALL: 'EMPLOYEES_DELETE_API_CALL',
  EMPLOYEES_DELETE_START: 'EMPLOYEES_DELETE_START',
  EMPLOYEES_DELETE_SUCCESS: 'EMPLOYEES_DELETE_SUCCESS',
  EMPLOYEES_DELETE_ERROR: 'EMPLOYEES_DELETE_ERROR',
};
