// import * as reduxActionNames from 'redux-action-names';
export default {
  DEPARTMENTS_CREATE_API_CALL: 'DEPARTMENTS_CREATE_API_CALL',
  DEPARTMENTS_CREATE_START: 'DEPARTMENTS_CREATE_START',
  DEPARTMENTS_CREATE_SUCCESS: 'DEPARTMENTS_CREATE_SUCCESS',
  DEPARTMENTS_CREATE_ERROR: 'DEPARTMENTS_CREATE_ERROR',

  DEPARTMENTS_FETCH_API_CALL: 'DEPARTMENTS_FETCH_API_CALL',
  DEPARTMENTS_FETCH_START: 'DEPARTMENTS_FETCH_START',
  DEPARTMENTS_FETCH_SUCCESS: 'DEPARTMENTS_FETCH_SUCCESS',
  DEPARTMENTS_FETCH_ERROR: 'DEPARTMENTS_FETCH_ERROR',

  DEPARTMENT_FETCH_API_CALL: 'DEPARTMENT_FETCH_API_CALL',
  DEPARTMENT_FETCH_START: 'DEPARTMENT_FETCH_START',
  DEPARTMENT_FETCH_SUCCESS: 'DEPARTMENT_FETCH_SUCCESS',
  DEPARTMENT_FETCH_ERROR: 'DEPARTMENT_FETCH_ERROR',

  DEPARTMENTS_UPDATE_API_CALL: 'DEPARTMENTS_UPDATE_API_CALL',
  DEPARTMENTS_UPDATE_START: 'DEPARTMENTS_UPDATE_START',
  DEPARTMENTS_UPDATE_SUCCESS: 'DEPARTMENTS_UPDATE_SUCCESS',
  DEPARTMENTS_UPDATE_ERROR: 'DEPARTMENTS_UPDATE_ERROR',

  DEPARTMENTS_DELETE_API_CALL: 'DEPARTMENTS_DELETE_API_CALL',
  DEPARTMENTS_DELETE_START: 'DEPARTMENTS_DELETE_START',
  DEPARTMENTS_DELETE_SUCCESS: 'DEPARTMENTS_DELETE_SUCCESS',
  DEPARTMENTS_DELETE_ERROR: 'DEPARTMENTS_DELETE_ERROR',
};
